Repository Treasure-Hunting/App, pull requests merged in 2019-11, with the labels that each got.

#2 (Close #1) バックエンド及びフロントエンドからファイルを追加
  .circleci/config.yml
  .gitignore
  manage.py
  oursite/__init__.py
  oursite/settings.py
  oursite/urls.py
  oursite/wsgi.py
  treasure/__init__.py
  treasure/admin.py
  treasure/apps.py
  treasure/fixtures/initial_data.json
  treasure/fixtures/test.json
  treasure/migrations/0001_initial.py
  treasure/migrations/0002_auto_20190909_1846.py
  treasure/migrations/0003_auto_20190916_1330.py
  treasure/migrations/0004_auto_20190917_1842.py
  treasure/migrations/0005_player_progress.py
  treasure/migrations/__init__.py
  treasure/models/__init__.py
  treasure/models/difficulty.py
  treasure/models/goal.py
  treasure/models/player.py
  treasure/models/quiz.py
  treasure/models/quiz_data.py
  treasure/static/back-prevent.js
  treasure/static/style/answer.css
  treasure/static/style/dif-sel.css
  treasure/static/style/go-goal.css
  treasure/static/style/hints.css
  treasure/static/style/last.css
  treasure/static/style/on-goal.css
  treasure/static/style/opening.css
  treasure/static/style/reset.css
  treasure/templates/treasure/404.html
  treasure/templates/treasure/answer.html
  treasure/templates/treasure/dif-sel.html
  treasure/templates/treasure/go-goal.html
  treasure/templates/treasure/hints.html
  treasure/templates/treasure/last.html
  treasure/templates/treasure/on-goal.html
  treasure/templates/treasure/opening.html
  treasure/templates/treasure/reset.html
  treasure/tests.py
  treasure/urls.py
  treasure/utility.py
  treasure/views.py
Labels: enhancement

#4 (Close #3) 静的ファイルを load static の後に読み込むよう修正
  treasure/templates/treasure/dif-sel.html
  treasure/templates/treasure/go-goal.html
  treasure/templates/treasure/hints.html
  treasure/templates/treasure/last.html
  treasure/templates/treasure/on-goal.html
  treasure/templates/treasure/opening.html
  treasure/templates/treasure/reset.html
Labels: bug

#6 (Close #5) README を追加
  README.md
Labels: documentation

#9 (Close #8) CI バッジのリポジトリ参照を修正
  README.md
Labels: bug, documentation

#14 Docker サポート
  .gitignore
  Dockerfile
  docker-compose.yml
  entrypoint.sh
  manage.py
  requirements.txt
  treasure_hunting/settings/__init__.py
  treasure_hunting/settings/common.py
  treasure_hunting/settings/development.py
  treasure_hunting/settings/production.py
Labels: enhancement, infrastructure

#16 (Close #15) entrypoint.sh に実行権限を追加
  entrypoint.sh
Labels: bug, infrastructure

#18 add ifequal to solve issue
  app/templates/app/answer.html
Labels: enhancement, frontend

#20 Heroku をサポート
  Dockerfile
  entrypoint.sh
  treasure_hunting/settings/production.py
Labels: enhancement, infrastructure

#25 (Close #23)answer.htmlでTemplateSyntaxError
  app/templates/app/answer.html
Labels: bug, frontend

#27 Update: Dockerfile optimization
  Dockerfile
Labels: infrastructure, refactoring

#28 (Close #26) Heroku に継続的デプロイ
  heroku.yml
Labels: infrastructure

#29 (Close #13) 難易度: Easy で選択肢が正常に表示されない問題を修正
  app/views.py
Labels: backend, bug

#12 (Close #11)trying set background-image
  app/static/img/easy.jpg
  app/static/img/goal.jpg
  app/static/img/hard.jpg
  app/static/img/normal.jpg
  app/static/img/opeing.jpg
  app/static/style/easy.css
  app/static/style/hard.css
  app/static/style/hints.css
  app/static/style/last.css
  app/static/style/normal.css
  app/static/style/opening.css
  app/templates/app/answer.html
  app/templates/app/go-goal.html
  app/templates/app/hints.html
  app/templates/app/last.html
  app/templates/app/opening.html
  app/views.py
Labels: enhancement, frontend

#31 (Close #21) テンプレートの共通部分切り出し
  app/static/style/answer.css
  app/static/style/common.css
  app/static/style/dif-sel.css
  app/static/style/go-goal.css
  app/static/style/hints.css
  app/static/style/on-goal.css
  app/static/style/opening.css
  app/static/style/reset.css
  app/templates/app/404.html
  app/templates/app/answer.html
  app/templates/app/base.html
  app/templates/app/dif-sel.html
  app/templates/app/go-goal.html
  app/templates/app/hints.html
  app/templates/app/last.html
  app/templates/app/on-goal.html
  app/templates/app/opening.html
  app/templates/app/reset.html
Labels: frontend, refactoring

#32 いくつかの IDE で静的ファイルを解決できるようにする
  treasure_hunting/settings/common.py
Labels: refactoring

#33 (Close #24) Bootstrap を使う
  app/static/style/common.css
  app/static/style/last.css
  app/static/style/reset.css
  app/templates/app/404.html
  app/templates/app/answer.html
  app/templates/app/base.html
  app/templates/app/dif-sel.html
  app/templates/app/go-goal.html
  app/templates/app/hints.html
  app/templates/app/last.html
  app/templates/app/on-goal.html
  app/templates/app/opening.html
  app/templates/app/reset.html
Labels: enhancement, frontend

#35 (Close #34) Google Fonts を読み込む
  app/static/style/common.css
Labels: enhancement, frontend

#37 (Close #36) WSGI で静的ファイルをサーブさせる
  treasure_hunting/wsgi.py
Labels: backend, bug

#38 (Close #11) 背景画像を追加
  app/static/img/default.jpg
  app/static/img/easy.jpg
  app/static/img/goal.jpg
  app/static/img/hard.jpg
  app/static/img/normal.jpg
  app/static/style/common.css
  app/static/style/easy.css
  app/static/style/goal.css
  app/static/style/hard.css
  app/static/style/normal.css
  app/templates/app/answer.html
  app/templates/app/base.html
  app/templates/app/dif-sel.html
  app/templates/app/go-goal.html
  app/templates/app/hints.html
  app/templates/app/last.html
  app/templates/app/on-goal.html
  app/templates/app/opening.html
  app/templates/app/reset.html
  app/views.py
Labels: enhancement, frontend

#41 (Close #40) 視認しづらい部分を修正
  app/static/style/common.css
  app/templates/app/reset.html
Labels: frontend

#43 (Close #42) クラスごとにファイルを分割
  app/models/__init__.py
  app/tests/__init__.py
  app/tests/goal_test.py
  app/tests/utility_test.py
  app/utility/__init__.py
  app/utility/conversion_table.py
  app/utility/conversion_table_resolver.py
  app/views.py
  app/views/__init__.py
  app/views/answer.py
  app/views/common.py
  app/views/dif_sel.py
  app/views/go_goal.py
  app/views/hints.py
  app/views/last.py
  app/views/on_goal.py
  app/views/opening.py
  app/views/progress_error.py
  app/views/reset.py
Labels: backend, refactoring

#45 (Close #44) 存在しない CSS ファイルへの参照を削除
  app/templates/app/opening.html
Labels: bug, frontend

#49 (Close #48)選択肢が間違っていた場合にエラーを表示する
  app/templates/app/answer.html
Labels: enhancement, frontend

#51 (Close #50)lastの画像を変更
  app/static/style/goal.css
Labels: bug, frontend

#53 (Close #52)fix last design
  app/templates/app/last.html
Labels: enhancement, frontend

#56 (Close #55) フィクスチャ修正
  app/fixtures/initial_data.json
  app/fixtures/second_data.json
Labels: backend, bug

#60 (Close #54) ボタンを押したあと無効化する
  app/static/button-disabler.js
  app/templates/app/base.html
Labels: enhancement, frontend

#61 (Close #47) Docker-Compose で PostgreSQL のデータディレクトリが正常にマウントできない問題を修正
  docker-compose.yml
Labels: bug, infrastructure

#62 (Close #39) back-prevent.js が正常に動作しない問題を修正
  app/static/back-prevent.js
Labels: bug, frontend

#64 順番整理
  app/views/go_goal.py
Labels: backend, enhancement

#68 初期データを修正
  app/fixtures/initial_data.json
Labels: backend, bug

#71 (Close #66) '宝探し' -> 'こうよう探険隊'
  app/templates/app/dif-sel.html
  app/templates/app/opening.html
Labels: frontend

#78 (Close #76) フィクスチャを注入する
  Dockerfile
  entrypoint.sh
Labels: infrastructure
